/**
 * Nome File: layout.js
 * Percorso: opero-shop/app/layout.js
 * Data: 16/12/2025
 * Descrizione: Layout principale (Root Layout) per l'applicazione Next.js.
 * Include gestione font e soppressione warning idratazione per compatibilità plugin browser.
 */

import localFont from "next/font/local";
import "./globals.css";

// Configurazione Font Geist Sans
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

// Configurazione Font Geist Mono
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Opero Shop",
  description: "Generated by Opero CMS",
};

export default function RootLayout({ children }) {
  return (
    // FIX: suppressHydrationWarning=true sul tag <html> è CRUCIALE.
    // Dice a React: "Ignora se trovi attributi extra (come quelli di Google Translate) in questo tag".
    // Impostiamo lang="it" come default corretto.
    <html lang="it" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}