/**
 * Layout per siti multi-tenant
 */
import "../../globals.css";

export const metadata = {
  title: "Opero Shop",
  description: "Generated by Opero Cloud CMS",
};

export default function SiteLayout({ children }) {
  return (
    <html lang="it">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}