/**
 * AI Site Generator Extension
 * Estende SiteGenerator.js per supportare siti AI-generated
 * Mantiene retrocompatibilità con sistema esistente
 */

const SiteGenerator = require('./SiteGenerator');
const { knex } = require('../config/db');

class AISiteGenerator extends SiteGenerator {
  constructor() {
    super();
  }

  /**
   * Genera sito completo da dati AI-enhanced
   */
  async generateAISite(websiteId, options = {}) {
    try {
      console.log(`🚀 Inizio generazione sito AI per websiteId: ${websiteId}`);

      // 1. Recupera dati sito con metadata AI
      const siteData = await this.getAISiteData(websiteId);

      // 2. Applica ottimizzazioni AI
      const optimizedData = await this.applyAIOptimizations(siteData, options);

      // 3. Usa SiteGenerator base per generazione
      const result = await this.generateSite(websiteId, {
        ...options,
        aiEnhanced: true,
        aiMetadata: siteData.aiMetadata
      });

      // 4. Applica post-processing AI
      await this.applyAIPostProcessing(result, optimizedData);

      return {
        ...result,
        aiEnhanced: true,
        aiOptimizations: optimizedData.aiOptimizations,
        generationTime: Date.now() - options.startTime
      };

    } catch (error) {
      console.error('Errore generazione sito AI:', error);
      throw error;
    }
  }

  /**
   * Recupera dati sito con informazioni AI
   */
  async getAISiteData(websiteId) {
    // Recupera dati base
    const siteData = await this.getSiteData(websiteId);

    // Aggiungi metadata AI
    const [aiMetadata] = await knex('siti_web_aziendali')
      .where({ id: websiteId })
      .select([
        'ai_generated',
        'ai_company_context',
        'ai_model_version',
        'ai_generation_metadata',
        'ai_suggestions',
        'ai_seo_optimizations',
        'ai_enhanced_content',
        'ai_last_analysis'
      ]);

    // Aggiungi pagine AI
    const pagesWithAI = await knex('pagine_sito_web')
      .where({ id_sito_web: websiteId })
      .select([
        '*',
        'ai_generated',
        'ai_generation_prompt',
        'ai_confidence_score',
        'ai_content_sections',
        'ai_enhancements',
        'ai_seo_metadata',
        'ai_optimized_for_mobile'
      ]);

    return {
      ...siteData,
      aiMetadata: aiMetadata || {},
      pages: pagesWithAI.map(page => ({
        ...page,
        contenuto_json: page.contenuto_json ? JSON.parse(page.contenuto_json) : {},
        aiMetadata: {
          ai_generated: page.ai_generated,
          confidence_score: page.ai_confidence_score,
          content_sections: page.ai_content_sections ? JSON.parse(page.ai_content_sections) : null,
          enhancements: page.ai_enhancements ? JSON.parse(page.ai_enhancements) : {},
          seo_metadata: page.ai_seo_metadata ? JSON.parse(page.ai_seo_metadata) : {},
          optimized_for_mobile: page.ai_optimized_for_mobile
        }
      }))
    };
  }

  /**
   * Applica ottimizzazioni AI ai dati del sito
   */
  async applyAIOptimizations(siteData, options) {
    const optimizations = {
      seo: {},
      performance: {},
      mobile: {},
      accessibility: {},
      content: {}
    };

    // SEO Optimizations
    if (siteData.aiMetadata?.ai_seo_optimizations) {
      optimizations.seo = {
        ...JSON.parse(siteData.aiMetadata.ai_seo_optimizations),
        autoGenerated: true
      };
    }

    // Content Optimizations
    optimizations.content = {
      aiGeneratedPages: siteData.pages.filter(p => p.aiMetadata.ai_generated).length,
      totalConfidence: this.calculateOverallConfidence(siteData.pages),
      enhancedSections: siteData.pages.reduce((acc, page) =>
        acc + (page.aiMetadata.enhancements?.sections?.length || 0), 0)
    };

    // Performance Optimizations
    optimizations.performance = {
      lazyLoadingImages: siteData.aiMetadata.ai_generated,
      optimizedImages: true,
      minifiedAssets: options.minify || false
    };

    // Mobile Optimizations
    optimizations.mobile = {
      responsiveDesign: true,
      touchOptimized: siteData.pages.some(p => p.aiMetadata.optimized_for_mobile),
      mobileFirst: true
    };

    return {
      ...siteData,
      aiOptimizations: optimizations
    };
  }

  /**
   * Applica post-processing AI alla generazione
   */
  async applyAIPostProcessing(result, optimizedData) {
    const { sitePath, siteData } = result;

    // 1. Genera sitemap.xml migliorato AI
    await this.generateAISitemap(sitePath, optimizedData);

    // 2. Genera robots.txt ottimizzato
    await this.generateAIRobotsTxt(sitePath, optimizedData);

    // 3. Crea file analytics AI
    await this.createAIAnalyticsFile(sitePath, optimizedData);

    // 4. Ottimizza immagini AI
    if (optimizedData.aiOptimizations.performance.optimizedImages) {
      await this.optimizeImages(siteData, sitePath);
    }

    return result;
  }

  /**
   * Genera sitemap con ottimizzazioni AI
   */
  async generateAISitemap(sitePath, siteData) {
    const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  ${siteData.pages.map(page => `
  <url>
    <loc>https://${siteData.site.domain || 'example.com'}/${page.slug}</loc>
    <lastmod>${page.updated_at || new Date().toISOString()}</lastmod>
    <changefreq>${this.getChangeFrequency(page)}</changefreq>
    <priority>${this.getPagePriority(page, siteData)}</priority>
    ${page.aiMetadata?.seo_metadata?.keywords ?
      `<image:image><image:loc>${this.getPrimaryImage(page)}</image:loc><image:caption>${page.aiMetadata.seo_metadata.keywords[0]}</image:caption></image:image>` : ''
    }
  </url>`).join('')}
</urlset>`;

    const fs = require('fs').promises;
    await fs.writeFile(`${sitePath}/public/sitemap.xml`, sitemap);
  }

  /**
   * Genera robots.txt ottimizzato AI
   */
  async generateAIRobotsTxt(sitePath, siteData) {
    const robots = `User-agent: *
Allow: /

# AI-generated rules based on content analysis
${siteData.aiOptimizations?.seo?.disallowRules || ''}

Sitemap: https://${siteData.site.domain || 'example.com'}/sitemap.xml

# AI optimization: Crawl delay for better performance
Crawl-delay: 1`;

    const fs = require('fs').promises;
    await fs.writeFile(`${sitePath}/public/robots.txt`, robots);
  }

  /**
   * Crea file analytics per tracking AI
   */
  async createAIAnalyticsFile(sitePath, siteData) {
    const analytics = {
      generated_at: new Date().toISOString(),
      ai_model: siteData.aiMetadata.ai_model_version,
      total_pages: siteData.pages.length,
      ai_generated_pages: siteData.aiOptimizations.content.aiGeneratedPages,
      confidence_score: siteData.aiOptimizations.content.totalConfidence,
      optimization_level: 'enhanced'
    };

    const fs = require('fs').promises;
    await fs.writeFile(`${sitePath}/ai-metadata.json`, JSON.stringify(analytics, null, 2));
  }

  /**
   * Ottimizza immagini generate da AI
   */
  async optimizeImages(siteData, sitePath) {
    // Implementazione ottimizzazione immagini
    console.log('🖼️ Ottimizzazione immagini AI...');

    // Qui andrebbero implementate:
    // - Compressione immagini
    // - Generazione formati moderni (WebP, AVIF)
    // - Lazy loading placeholder
    // - Responsive image sets
  }

  /**
   * Calcola confidence score complessivo
   */
  calculateOverallConfidence(pages) {
    const aiPages = pages.filter(p => p.aiMetadata.ai_generated);
    if (aiPages.length === 0) return 0;

    const totalConfidence = aiPages.reduce((sum, page) =>
      sum + (page.aiMetadata.confidence_score || 0), 0);

    return totalConfidence / aiPages.length;
  }

  /**
   * Determina frequenza di aggiornamento basata su AI
   */
  getChangeFrequency(page) {
    if (page.aiMetadata?.ai_generated) {
      return 'weekly'; // Pagine AI potrebbero essere aggiornate spesso
    }

    return page.slug === 'home' ? 'daily' : 'monthly';
  }

  /**
   * Calcola priorità pagina basata su AI
   */
  getPagePriority(page, siteData) {
    if (page.aiMetadata?.ai_generated && page.aiMetadata.confidence_score > 0.8) {
      return '0.9'; // Alta priorità per pagine AI di alta qualità
    }

    if (page.slug === 'home') return '0.8';
    if (page.slug.includes('contatti')) return '0.7';

    return '0.6';
  }

  /**
   * Estrai immagine primaria da pagina AI
   */
  getPrimaryImage(page) {
    // Estrai immagini da contenuto AI se disponibili
    if (page.aiMetadata?.enhancements?.images) {
      return page.aiMetadata.enhancements.images[0];
    }

    return '/placeholder-image.jpg';
  }

  /**
   * Deploy sito AI con ottimizzazioni automatiche
   */
  async deployAISite(websiteId, vpsConfig, deployOptions = {}) {
    try {
      console.log('🚀 Deploy sito AI con ottimizzazioni...');

      // Genera sito con AI enhancements
      const generationResult = await this.generateAISite(websiteId, {
        ...deployOptions,
        startTime: Date.now()
      });

      // Aggiorna metadata deploy
      await knex('siti_web_aziendali')
        .where({ id: websiteId })
        .update({
          deploy_status: 'deploying',
          ai_last_analysis: new Date(),
          total_deploys: knex.raw('total_deploys + 1'),
          updated_at: new Date()
        });

      // Deploy con sistema VPS esistente
      const VPSDeployer = require('./VPSDeployer');
      const deployer = new VPSDeployer();

      const deployResult = await deployer.deploy({
        siteId: websiteId,
        sitePath: generationResult.sitePath,
        vpsConfig,
        aiEnhanced: true,
        optimizations: generationResult.aiOptimizations
      });

      // Aggiorna stato finale
      await knex('siti_web_aziendali')
        .where({ id: websiteId })
        .update({
          deploy_status: 'deployed',
          deployed_at: new Date(),
          last_deploy_success: new Date(),
          published_url: deployResult.siteUrl,
          deploy_error: null
        });

      return {
        ...deployResult,
        aiEnhanced: true,
        aiOptimizations: generationResult.aiOptimizations,
        generationTime: generationResult.generationTime,
        deployTime: Date.now() - generationResult.startTime - generationResult.generationTime
      };

    } catch (error) {
      console.error('Errore deploy sito AI:', error);

      // Aggiorna stato errore
      await knex('siti_web_aziendali')
        .where({ id: websiteId })
        .update({
          deploy_status: 'error',
          deploy_error: error.message
        });

      throw error;
    }
  }
}

module.exports = AISiteGenerator;